Alquiler_sqlite/Alquiler/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
#from django.conf.urls.statics import static 

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^banco/' , include('bancos.urls', namespace='bancos')),
    url(r'^caja/' , include('cajas.urls', namespace='cajas')),
    url(r'^cobranza/', include('cobranzas.urls', namespace='cobranzas')),
    url(r'^contrato/' , include('contratos.urls', namespace='contratos')),
    url(r'^gasto/' , include('gastos.urls', namespace='gastos')),
    url(r'^inquilino/' , include('inquilinos.urls', namespace='inquilinos')),
    url(r'^local/' , include('locales.urls', namespace='locales')),
    url(r'^lote/' , include('lotes.urls', namespace='lotes')),
    url(r'^mantenimiento/' , include('mantenimientos.urls', namespace='mantenimientos')),
    url(r'^pago/' , include('pagos.urls', namespace='pagos')),
] # + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Alquiler_sqlite/cajas/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.CajaList.as_view(), name='list'),
	url(r'^(?P<pk>\d+)$', views.CajaDetail.as_view(), name='detail'),
	url(r'^nuevo$', views.CajaCreation.as_view(), name='new'),
	url(r'^editar/(?P<pk>\d+)$', views.CajaUpdate.as_view(), name='edit'),
]

Alquiler_sqlite/lotes/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.LoteList.as_view(), name='list'),
	url(r'^(?P<pk>\d+)$', views.LoteDetail.as_view(), name='detail'),
	url(r'^nuevo$', views.LoteCreation.as_view(), name='new'),
	url(r'^editar/(?P<pk>\d+)$', views.LoteUpdate.as_view(), name='edit'),
	url(r'^transaccion/$', views.LoteTransaccionContratoList.as_view(), name='transaction'),
	url(r'^transaccion/([0-9]{4})-([0-9]{1})$', views.LoteTransaccionContratoList.as_view(), name='transaction'),
	url(r'^transaccion/nueva_cobranza/$', views.LoteNuevaCobranzaCreation.as_view(), name='new_cobranza'),
	url(r'^transaccion/editar_cobranza/(?P<pk>\d+)$', views.LoteNuevaCobranzaUpdate.as_view(), name='edit_cobranza'),
	#url(r'^transaccion/nuevo_pago/([0-9]{4})-([0-9]{1})$', views.LoteNuevoPagoCreation.as_view(), name='new_Pago'),
	url(r'^transaccion/nuevo_pago$', views.LoteNuevoPagoCreation.as_view(), name='new_Pago'),
	url(r'^lotecobranza/$', views.LoteCobranzaList.as_view(), name='list_lotecobranza'),
	url(r'^lotecobranza/nueva/$', views.LoteCobranzaCreation.as_view(), name='new_lotecobranza'),
	url(r'^lotecobranza/editar/(?P<pk>\d+)$', views.LoteCobranzaUpdate.as_view(), name='edit_lotecobranza'),	
]

Alquiler_sqlite/lotes/models.py
from __future__ import unicode_literals

from django.db import models

from cobranzas.models import Cobranza
from pagos.models import Pago


class Lote(models.Model):
	numero = models.CharField(max_length=255, unique=True)
	inicio = models.DateField()

	class Meta:
		ordering = ('numero',)

	def __str__(self):
		return self.numero


class LoteCierre(models.Model):
	lote = models.OneToOneField(Lote, primary_key=True)
	fecha = models.DateField()
	cobrado = models.DecimalField(max_digits=7, decimal_places=2)
	gasto = models.DecimalField(max_digits=7, decimal_places=2)
	total = models.DecimalField(max_digits=7, decimal_places=2)

	class Meta:
		ordering = ('lote',)

	def __str__(self):
		return u'%s' % (self.fecha)


class LoteRevisado(models.Model):
	lote = models.OneToOneField(Lote, primary_key=True)
	fecha = models.DateField()

	class Meta:
		ordering = ('lote',)

	def __str__(self):
		return u'%s' % (self.fecha)


class LoteCobranza(models.Model):
	cobranza = models.OneToOneField(Cobranza, primary_key=True)
	lote = models.ForeignKey(Lote)


class LotePago(models.Model):
	pago = models.OneToOneField(Pago, primary_key=True)
	lote = models.ForeignKey(Lote)

Alquiler_sqlite/lotes/forms.py
from django import forms
from django.contrib.admin import widgets

from .models import LoteCobranza, Lote, LotePago
from cobranzas.models import Cobranza, CobranzaTipo
from cobranzas.forms import CobranzaForm
from pagos.forms import PagoForm 


class LoteNuevaCobranzaForm(CobranzaForm):
	def __init__(self, *args, **kwargs):
		super(LoteNuevaCobranzaForm, self).__init__(*args, **kwargs)
		tipo = CobranzaTipo.objects.values('id').filter(nombre='Contrato')
		self.fields['tipo'].initial = tipo[0]['id']


LoteCobranzaFormSet = forms.inlineformset_factory(Cobranza, LoteCobranza, can_delete=False, fields=('lote',))


class LoteEditarCobranzaForm(forms.ModelForm):
	class Meta():
		model = Cobranza
		fields = ['tipo', 'contrato', 'periodo', 'fecha', 'monto']
		widgets = {
			'fecha': forms.DateInput(attrs={'id': 'datepicker'})
		}


class LotePagoForm(forms.ModelForm):
	class Meta():
		model = LotePago
		fields = ['lote', 'pago']

Alquiler_sqlite/lotes/views.py
from django.db.models import Sum
from django.http import HttpResponseRedirect

from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import (
	CreateView,
	UpdateView,
)

from .models import Lote, LoteCobranza, LotePago
from cobranzas.models import Cobranza
from pagos.models import Pago, PagoMantenimiento, PagoGasto
from cajas.models import Caja, CajaLote
from bancos.models import Banco, BancoLote

from cobranzas.views import CobranzaList
from pagos.views import PagoCreation

from .forms import (LoteNuevaCobranzaForm, LoteCobranzaFormSet, 
	LoteEditarCobranzaForm, LotePagoForm)
from pagos.forms import PagoForm, PagoMantenimientoForm, PagoGastoForm
from mantenimientos.forms import MantenimientoForm, MantenimientoPeriodoForm


class LoteList(ListView):
	model = Lote

	def get_context_data(self, **kwargs):
		context = super(LoteList, self).get_context_data(**kwargs)
		context.update({'titulo': 'Lista de Lote'})
		return context


class LoteDetail(DetailView):
	model = Lote

	def get_context_data(self, **kwargs):
		context = super(LoteDetail, self).get_context_data(**kwargs)
		context.update({'titulo': 'Detalle de Lote'})
		return context


class LoteCreation(CreateView):
	model = Lote
	success_url = reverse_lazy('lotes:list')
	fields = ['id', 'numero', 'inicio', 'cierre', 'cobrado', 'gasto', 'total',
			  'revisado'] 

	def get_context_data(self, **kwargs):
		context = super(LoteCreation, self).get_context_data(**kwargs)
		context.update({'titulo': 'Nuevo Lote'})
		return context


class LoteUpdate(UpdateView):
	model = Lote
	success_url = reverse_lazy('lotes:list')
	fields = ['id', 'numero', 'inicio']

	def get_context_data(self, **kwargs):
		context = super(LoteUpdate, self).get_context_data(**kwargs)
		context.update({'titulo': 'Editar Lote'})
		return context


class LoteCobranzaList(ListView):
	model = LoteCobranza 

	def get_context_data(self, **kwargs):
		context = super(LoteCobranzaList, self).get_context_data(**kwargs)
		context.update({'titulo': 'Lista Lote de Cobranzas'})
		return context


class LoteCobranzaCreation(CreateView):
	model = LoteCobranza
	success_url = reverse_lazy('lotes:list_lotecobranza')
	fields = ['cobranza', 'lote'] 

	def get_context_data(self, **kwargs):
		context = super(LoteCobranzaCreation, self).get_context_data(**kwargs)
		context.update({'titulo': 'Nuevo Lote de Cobranza'})
		return context


class LoteCobranzaUpdate(UpdateView):
	model = LoteCobranza 
	success_url = reverse_lazy('lotes:list_lotecobranza')
	fields = ['cobranza', 'lote']

	def get_context_data(self, **kwargs):
		context = super(LoteCobranzaUpdate, self).get_context_data(**kwargs)
		context.update({'titulo': 'Editar Lote de Cobranza'})
		return context


class LoteTransaccionContratoList(ListView):
	#model = Lote
	context_object_name = 'ultimo_lote'  
	template_name = 'lotes/lotetransaccioncontrato_list.html'
	#queryset = Lote.objects.order_by('id').last()

	def get_queryset(self):
		if self.args == ():
			return Lote.objects.order_by('id').last()
		else:
			return Lote.objects.get(numero=(self.args[0] + "-" + self.args[1]))

	def get_context_data(self, **kwargs):
		context = super(LoteTransaccionContratoList, self).get_context_data(
			**kwargs)
		lote_cobranza = LoteCobranza.objects.filter(
			lote=context['ultimo_lote'], cobranza__tipo__id=1)
		cobranza_total = LoteCobranza.objects.filter(
			lote=context['ultimo_lote'], cobranza__tipo__id=1).aggregate(
			total=Sum('cobranza__monto'))
		lote_pago = LotePago.objects.filter(
			lote=context['ultimo_lote'])
		pago_mantenimiento = PagoMantenimiento.objects.all()
		pago_gasto = PagoGasto.objects.all()
		rango_med = context['ultimo_lote']
		rango_inicio = rango_med.id - 20
		ultimo = Lote.objects.order_by('id').last()
		rango_final = ultimo.id
		lote_lista = Lote.objects.filter(id__range=[rango_inicio, rango_final])

		context.update({'titulo': 'Transacciones'})
		context.update({'lote_cobranza': lote_cobranza})
		context.update({'cobranza_total': cobranza_total})
		context.update({'lote_pago': lote_pago})
		context.update({'pago_mantenimiento': pago_mantenimiento})
		context.update({'pago_gasto': pago_gasto})
		context.update({'lote_lista': lote_lista})
		return context

class LoteNuevaCobranzaCreation(CreateView):
	template_name = 'lotes/lotenuevacobranza_form.html'
	success_url = reverse_lazy('lotes:transaction')
	form_class = LoteNuevaCobranzaForm
	
	def get(self, request, *args, **kwargs):
		"""
		Handles GET requests and instantiates blank versions of the form
		and its inline formsets.
		"""
		self.object = None
		form_class = self.get_form_class()
		form = self.get_form(form_class)
		ultimo_lote_id = Lote.objects.order_by('id').last()
		lotecobranza_form = LoteCobranzaFormSet(initial=[{'lote': ultimo_lote_id}])
		return self.render_to_response(self.get_context_data(form=form, lotecobranza_form=lotecobranza_form))

	def post(self, request, *args, **kwargs):
		"""
		Handles POST requests, instantiating a form instance and its inline
		formsets with the passed POST variables and then checking them for
		validity.
		"""
		self.object = None
		form_class = self.get_form_class()
		form = self.get_form(form_class)
		lotecobranza_form = LoteCobranzaFormSet(self.request.POST)
		if (form.is_valid() and lotecobranza_form.is_valid()):
		    return self.form_valid(form, lotecobranza_form)
		else:
		    return self.form_invalid(form, lotecobranza_form)

	def form_valid(self, form, lotecobranza_form):
		"""
		Called if all forms are valid. Creates a Recipe instance along with
		associated Ingredients and Instructions and then redirects to a
		success page.
		"""
		self.object = form.save()
		lotecobranza_form.instance = self.object
		lotecobranza_form.save()
		return HttpResponseRedirect(self.get_success_url())

	def form_invalid(self, form, lotecobranza_form):
		"""
		Called if a form is invalid. Re-renders the context data with the
		data-filled forms and errors.
		"""
		return self.render_to_response(
		self.get_context_data(form=form,
		                      lotecobranza_form=lotecobranza_form))
		

class LoteNuevaCobranzaUpdate(UpdateView):
	model = Cobranza 
	template_name = 'lotes/loteeditarcobranza_form.html'
	success_url = reverse_lazy('lotes:transaction')
	form_class = LoteEditarCobranzaForm

	def get(self, request, *args, **kwargs):
		"""
		Handles GET requests and instantiates blank versions of the form
		and its inline formsets.
		"""
		self.object = self.get_object()
		form_class = self.get_form_class()
		form = self.get_form(form_class)
		ultimo_lote_id = Lote.objects.order_by('id').last()
		lotecobranza_form = LoteCobranzaFormSet(initial=[{'lote': ultimo_lote_id}])
		return self.render_to_response(self.get_context_data(form=form, lotecobranza_form=lotecobranza_form))

	def post(self, request, *args, **kwargs):
		"""
		Handles POST requests, instantiating a form instance and its inline
		formsets with the passed POST variables and then checking them for
		validity.
		"""
		self.object = self.get_object()
		form_class = self.get_form_class()
		form = self.get_form(form_class)
		lotecobranza_form = LoteCobranzaFormSet(self.request.POST)
		if (form.is_valid() and lotecobranza_form.is_valid()):
		    return self.form_valid(form, lotecobranza_form)
		else:
		    return self.form_invalid(form, lotecobranza_form)

	def form_valid(self, form, lotecobranza_form):
		"""
		Called if all forms are valid. Creates a Recipe instance along with
		associated Ingredients and Instructions and then redirects to a
		success page.
		"""
		self.object = form.save()
		lotecobranza_form.instance = self.object
		lotecobranza_form.save()
		return HttpResponseRedirect(self.get_success_url())

	def form_invalid(self, form, lotecobranza_form):
		"""
		Called if a form is invalid. Re-renders the context data with the
		data-filled forms and errors.
		"""
		return self.render_to_response(
		self.get_context_data(form=form,
		                      lotecobranza_form=lotecobranza_form))

class LoteNuevoPagoCreation(CreateView):
	template_name = 'lotes/lotenuevopago_form.html'
	success_url = reverse_lazy('lotes:transaction')
	form_class = PagoForm

	def get_context_data(self, *args, **kwargs):
		context = super(LoteNuevoPagoCreation, self).get_context_data(**kwargs)
		context.update({'titulo': 'Nuevo Pago Lote'})
		return context

	def get(self, request, *args, **kwargs):
		"""
		Handles GET requests and instantiates blank versions of the form
		and its inline formsets.
		"""
		self.object = None
		form_class = self.get_form_class()
		form = self.get_form(form_class)
		# prueba post pagomantenimiento_form = PagoMantenimientoForm()
		# prueba post mantenimientoperiodo_form = MantenimientoPeriodoForm()
		return self.render_to_response(self.get_context_data(form=form, 
			#pagomantenimiento_form=pagomantenimiento_form,
			#mantenimientoperiodo_form=mantenimientoperiodo_form,
			))


	def post(self, request, *args, **kwargs):
		"""
		Handles POST requests, instantiating a form instance and its inline
		formsets with the passed POST variables and then checking them for
		validity.
		"""
		self.object = None
		tipopago = self.request.POST.get('monto')
		tipo = self.request.POST.get('tipo')
		form_class = self.get_form_class()
		form = self.get_form(form_class)

		if not tipopago:
			mantenimientoperiodo_form = MantenimientoPeriodoForm()
			pagomantenimiento_form = PagoMantenimientoForm()
			pagogasto_form = PagoGastoForm()

			if (tipo == '1'):
				return self.render_to_response(self.get_context_data(form=form, 
					mantenimientoperiodo_form=mantenimientoperiodo_form,
					pagomantenimiento_form=pagomantenimiento_form,
					))

			if (tipo == '2'):
				return self.render_to_response(self.get_context_data(form=form, 
					pagogasto_form=pagogasto_form,
					))

		if (tipo == '1'):
			mantenimientoperiodo_form = MantenimientoPeriodoForm(self.request.POST)

Alquiler_sqlite/templates/lotes/lote_detail.html
{% extends "base.html" %}

{% block page_title %}
    {{ titulo }}
{% endblock %}

{% block contenido %}
	<h1>Numero: <i>{{ lote.numero }}</i></h1>
	<p>Inicio: <i>{{ lote.inicio }}</i></p>
	<p>Cierre: <i>{{ lote.cierre }}</i></p>
	<p>Cobrado: <i>{{ lote.cobrado }}</i></p>
	<p>Gasto: <i>{{ lote.gasto }}</i></p>
	<p>Total: <i>{{ lote.total }}</i></p>
	<p>Revisado: <i>{{ lote.revisado }}</i></p>
	<p>
	    <a href="{% url "lotes:list" %}">Regresar</a>
	</p>
{% endblock %}

Alquiler_sqlite/templates/lotes/lote_form.html
{% extends "base.html" %}

{% block page_title %}
    {{ titulo }}
{% endblock %}

{% block contenido %}
	<form method="post">
	    {% csrf_token %}
	    {{ form.as_p }}
	    <input type="submit" class="Canvas-main-button-grabar" value="Guardar" />
		<input type="button" class="Canvas-main-button-regresar" onclick="goBack()" value="Regresar" />
	</form>
{% endblock %}

Alquiler_sqlite/templates/lotes/lote_list.html
{% extends "base.html" %}

{% block page_title %}
    {{ titulo }}
{% endblock %}

{% block contenido %}
    {% include "form-button.html" with urldir="lotes:new" %}
    <table id="listaLote" class="Table-lista">
        <caption>{{ titulo }}</caption>
        <thead>
            <tr>
                <th>NUMERO</th>
                <th>INICIO</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        {% for lt in object_list %}
            <tr>
                <td>{{ lt.numero }}</td>
                <td>{{ lt.inicio }}</td>
                <td><a href="{% url "lotes:detail" lt.id %}">Ver</a></td>
                <td><a href="{% url "lotes:edit" lt.id %}">Editar</a></td>
            </tr>
        {% endfor %}
        </tbody>     
    </table>
{% endblock %}

Alquiler_sqlite/templates/lotes/lotecobranza_form.html
{% extends "base.html" %}

{% block page_title %}
    {{ titulo }}
{% endblock %}

{% block contenido %}
	<form method="post">
	    {% csrf_token %}
	    {{ form.as_p }}
	    <input type="submit" class="Canvas-main-button-grabar" value="Guardar" />
		<input type="button" class="Canvas-main-button-regresar" onclick="goBack()" value="Regresar" />
	</form>
{% endblock %}

Alquiler_sqlite/templates/lotes/lotecobranza_list.html
{% extends "base.html" %}

{% block page_title %}
    {{ titulo }}
{% endblock %}

{% block contenido %}
    {% include "form-button.html" with urldir="lotes:new_lotecobranza" %}
    <table id="listaLotecobranza" class="Table-lista">
        <caption>{{ titulo }}</caption>
        <thead>
            <tr>
                <th>ID</th>
                <th>COBRANZA</th>
                <th>LOTE</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        {% for lt in object_list %}
            <tr>
                <td>{{ lt.pk }}</td>
                <td>{{ lt.cobranza.pk }}</td>
                <td>{{ lt.lote.pk }}</td>
                <td><a href="{% url "lotes:edit_lotecobranza" lt.pk %}">Editar</a></td>
            </tr>
        {% endfor %}
        </tbody>     
    </table>
    <script type="text/javascript">
        $(function(){
            BotonAgregar();
        })
    </script>    
{% endblock %}

Alquiler_sqlite/templates/lotes/loteeditarcobranza_form.html
{% extends "base.html" %}

{% block page_title %}
    {{ titulo }}
{% endblock %}

{% block contenido %}
	<form action="" method="post">
	    {% csrf_token %}
	    {{ form.as_p }}
	    {{ lotecobranza_form.as_p }}
	    <input type="submit" class="Canvas-main-button-grabar" value="Guardar" />
		<input type="button" class="Canvas-main-button-regresar" onclick="goBack()" value="Regresar" />
	</form>
{% endblock %}

Alquiler_sqlite/templates/lotes/lotenuevacobranza_form.html
{% extends "base.html" %}

{% block page_title %}
    {{ titulo }}
{% endblock %}

{% block contenido %}
	<form method="post">
	    {% csrf_token %}
	    {{ form.as_p }}
	    {{ lotecobranza_form.as_p }}
	    <input type="submit" class="Canvas-main-button-grabar" value="Guardar" />
		<input type="button" class="Canvas-main-button-regresar" onclick="goBack()" value="Regresar" />
	</form>
{% endblock %}

Alquiler_sqlite/templates/lotes/lotenuevopago_form.html
{% extends "base.html" %}

{% block page_title %}
    {{ titulo }}
{% endblock %}

{% block contenido %}
	<form method="post">
	    {% csrf_token %}
	    {{ form.as_p }}
	    {{ mantenimientoperiodo_form.as_p}}
	    {{ pagomantenimiento_form.as_p}}
	    {{ pagogasto_form.as_p}}
	    <input type="submit" class="Canvas-main-button-grabar" value="Guardar" />
		<input type="button" class="Canvas-main-button-regresar" onclick="goBack()" value="Regresar" />
	</form>
	<script type="text/javascript">
        $(function(){
        	$("#datepicker").datepicker({dateFormat: 'dd/mm/yy'});
            EnviarMesAnio();
            SumarColumna('listaPago', 5);
            PonerComaColumna('listaPago', 5);
            MesPredeterminado("{{ month }}")
        })
    </script>
{% endblock %}

Alquiler_sqlite/templates/lotes/lotetransaccioncontrato_list.html
{% extends "base.html" %}

{% block page_title %}
	{{ titulo }}
{% endblock %}

{% block contenido %}
	<form id="form_month_year" class="Canvas-main-form_month_year">
        <label>Lote :</label>
        <input type="text" id="lote" list="lotelist" value="{{ ultimo_lote }}" />
        <datalist id="lotelist" name="lotelist">
        	{% for lo in lote_lista %}
            	<option value="{{ lo.numero }}">{{ lo.numero }}</option>
            {% endfor %}
        </datalist>
        <input type="button" id="submitfiltro" value="Filtrar" />
    </form>
    <button id="Canvas-main-button" class="Canvas-main-button" name="{% url "lotes:new_cobranza" %}">Agregar Cobranza</button>
    <p>{{ rango_med }}</p>

	<table id="listaCobranza" class="Table-lista">
		<caption>Cobranzas</caption>
		<thead>
			<th>NUM. COBR.</th>
			<th>CONTRATO</th>
			<th>LOCAL</th>
			<th>PERIODO</th>
			<th>F. COBRANZA</th>
			<th>MONTO</th>
		</thead>
		<tbody>
		{% for lt in lote_cobranza %}
			<tr>
  				<td><a href="{% url "lotes:edit_cobranza" lt.pk %}" >{{ lt.pk }}</a></td>
    			<td>{{ lt.cobranza.contrato.id }}</td>
    			<td>{{ lt.cobranza.contrato.local }}</td>
    			<td>{{ lt.cobranza.periodo }}</td>
    			<td>{{ lt.cobranza.fecha }}</td>
    			<td class="Table-lista-aligright">{{ lt.cobranza.monto }}</td>
			</tr>
		{% endfor %}
		</tbody>
		<tfoot>
			<tr>
				<th></th>
				<th></th>
				<th></th>
				<th></th>
				<th>Total</th>
				<th class="Table-lista-aligright"></th>
			</tr>
		</tfoot>
	</table>
	<br /><br />
	<button id="Canvas-main-button" class="Canvas-main-button" name="{% url "lotes:new_Pago" %}">Agregar Pago</button>
	<table id="listaPago" class="Table-lista">
		<caption>Pagos</caption>
		<thead>
			<tr>
				<th>NUM. PAGO</th>
				<th>TIPO</th>
				<th>FECHA</th>
				<th>GRUPO</th>
				<th>NOMBRE</th>
				<th>MONTO</th>
			</tr>
		</thead>
		<tbody>
		{% for lt in lote_pago %}
            <tr>
  				<td><a href="" >{{ lt.pago.id }}</a></td>
                <td>{{ lt.pago.tipo.nombre }}</td>
                <td>{{ lt.pago.fecha }}</td>
                {% if lt.pago.tipo.id = 1 %}
                    {% for pm in pago_mantenimiento %}
                        {% if pm.pago.pk == lt.pago.id %}
                            <td>{{ pm.mantenimiento_periodo.mantenimiento.grupo }}</td>
                            <td>{{ pm.mantenimiento_periodo.mantenimiento.nombre }}</td>
                            <td class="Table-lista-aligright">{{ pm.monto }}</td>
                        {% endif %}
                    {% endfor %}
                {% else %}
                    {% for pg in pago_gasto %}
                        {% if pg.pago.pk == lt.pago.id %}
                            <td>{{ pg.gasto.grupo }}</td>
                            <td>{{ pg.gasto.nombre }}</td>
                            <td class="Table-lista-aligright">{{ pg.monto }}</td>
                        {% endif %}
                    {% endfor %}
                {% endif %}
            </tr>
		{% endfor %}
		</tbody>
		<tfoot>
			<tr>
				<th></th>
				<th></th>
				<th></th>
				<th></th>
				<th>Total</th>
				<th class="Table-lista-aligright"></th>
			</tr>
		</tfoot>
	</table>
	<script type="text/javascript">
        $(function(){
            BotonAgregar();
            SumarColumna('listaCobranza', 5);
            SumarColumna('listaPago', 5);
            PonerComaColumna('listaCobranza', 5);
            PonerComaColumna('listaPago', 5);
            EnviarLote('lote/transaccion');
        })
    </script>
{% endblock %}