Alquiler_sqlite/Alquiler/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
#from django.conf.urls.statics import static 

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^banco/' , include('bancos.urls', namespace='bancos')),
    url(r'^caja/' , include('cajas.urls', namespace='cajas')),
    url(r'^cobranza/', include('cobranzas.urls', namespace='cobranzas')),
    url(r'^contrato/' , include('contratos.urls', namespace='contratos')),
    url(r'^gasto/' , include('gastos.urls', namespace='gastos')),
    url(r'^inquilino/' , include('inquilinos.urls', namespace='inquilinos')),
    url(r'^local/' , include('locales.urls', namespace='locales')),
    url(r'^lote/' , include('lotes.urls', namespace='lotes')),
    url(r'^mantenimiento/' , include('mantenimientos.urls', namespace='mantenimientos')),
    url(r'^pago/' , include('pagos.urls', namespace='pagos')),
] # + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Alquiler_sqlite/cajas/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.CajaList.as_view(), name='list'),
	url(r'^(?P<pk>\d+)$', views.CajaDetail.as_view(), name='detail'),
	url(r'^nuevo$', views.CajaCreation.as_view(), name='new'),
	url(r'^editar/(?P<pk>\d+)$', views.CajaUpdate.as_view(), name='edit'),
]

Alquiler_sqlite/cobranzas/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.CobranzaList.as_view(), name='list'),
	url(r'^([0-9]{2})/([0-9]{4})$', views.CobranzaList.as_view(), name='list'),
	url(r'^(?P<pk>\d+)$', views.CobranzaDetail.as_view(), name='detail'),
	url(r'^nuevo$', views.CobranzaCreation.as_view(), name='new'),
	url(r'^editar/(?P<pk>\d+)$', views.CobranzaUpdate.as_view(), name='edit'),
	url(r'^estadocuenta/$', views.EstadoCuentaList.as_view(), name='cuenta'),
	url(r'^estadocuenta/([0-9]{2})/([0-9]{4})$', views.EstadoCuentaList.as_view(), name='cuenta'),

]

Alquiler_sqlite/lotes/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.LoteList.as_view(), name='list'),
	url(r'^(?P<pk>\d+)$', views.LoteDetail.as_view(), name='detail'),
	url(r'^nuevo$', views.LoteCreation.as_view(), name='new'),
	url(r'^editar/(?P<pk>\d+)$', views.LoteUpdate.as_view(), name='edit'),
	url(r'^transaccion/$', views.LoteTransaccionContratoList.as_view(), name='transaction'),
	url(r'^transaccion/([0-9]{4})-([0-9]{1})$', views.LoteTransaccionContratoList.as_view(), name='transaction'),
	url(r'^transaccion/nueva_cobranza/$', views.LoteNuevaCobranzaCreation.as_view(), name='new_cobranza'),
	url(r'^transaccion/editar_cobranza/(?P<pk>\d+)$', views.LoteNuevaCobranzaUpdate.as_view(), name='edit_cobranza'),
	#url(r'^transaccion/nuevo_pago/([0-9]{4})-([0-9]{1})$', views.LoteNuevoPagoCreation.as_view(), name='new_Pago'),
	url(r'^transaccion/nuevo_pago$', views.LoteNuevoPagoCreation.as_view(), name='new_Pago'),
	url(r'^lotecobranza/$', views.LoteCobranzaList.as_view(), name='list_lotecobranza'),
	url(r'^lotecobranza/nueva/$', views.LoteCobranzaCreation.as_view(), name='new_lotecobranza'),
	url(r'^lotecobranza/editar/(?P<pk>\d+)$', views.LoteCobranzaUpdate.as_view(), name='edit_lotecobranza'),	
]

Alquiler_sqlite/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	{% load staticfiles %}
	<meta charset="UTF-8">
	<title>{% block page_title %}{% endblock %}</title>
	<meta name="viewport" content="width=device-width, user-scalabel=no">
	<link rel="stylesheet" href="{% static 'css/normalize.css' %}">
	<link rel="stylesheet" href="{% static 'css/base.css' %}">
	<link rel="stylesheet" href="http://code.jquery.com/ui/1.11.3/themes/smoothness/jquery-ui.css">
	<script type="text/javascript" src="{% static 'js/base.js' %}"></script>
	<script type="text/javascript" src="http://code.jquery.com/jquery-2.2.4.min.js"></script>
	<script type="text/javascript" src="http://code.jquery.com/ui/1.11.3/jquery-ui.min.js"></script>
</head>
<body>
	<section class="Canvas">
		<header class="Header is-active">
			<h1 class="Header-logo">
				<a href="">Proyecto Alquiler de Stand</a>
			</h1>
			<button class="Header-button">Menú</button>
			<ul class="MainMenu">
				<li class="MainMenu-item">
					<a href="{% url "lotes:transaction" %}" class="MainMenu-link">Lote</a>
				</li>
				<li class="MainMenu-item">
					<a href="{% url "cobranzas:list" %}" class="MainMenu-link">Cobranza</a>
				</li>
				<li class="MainMenu-item">
					<a href="{% url "cobranzas:cuenta" %}" class="MainMenu-link">Estado</a>
				</li>
				<li class="MainMenu-item">
					<a href="{% url "pagos:list" %}" class="MainMenu-link">Pago</a>
				</li>
			</ul>
			<div class="Header-login">
				<button class="Header-buttonlogin">Cerrar_sesión</button>
			</div>
		</header>
		<article class="Canvas-main">
			<section>
				{% block contenido %}
				{% endblock %}
			</section>
		</article>
		<footer>
			{% block pie %}
			{% endblock %}
		</footer>
	</section>
</body>
</html>

Alquiler_sqlite/templates/form-button.html
<form id="form_month_year" class="Canvas-main-form_month_year">
    <label>Mes :</label>
    <select id="month" name="month">
        <option value="01" >Enero</option>
        <option value="02">Febrero</option>
        <option value="03">Marzo</option>
        <option value="04">Abril</option>
        <option value="05">Mayo</option>
        <option value="06">Junio</option>
        <option value="07">Julio</option>
        <option value="08">Agosto</option>
        <option value="09">Setiembre</option>
        <option value="10">Octubre</option>
        <option value="11">Noviembre</option>
        <option value="12">Diciembre</option>
    </select>
    <label>Año :</label>
    <input type="text" id="year" name="year" value={{ year }} />
    <input type="button" id="submit" value="Filtrar" />
</form>
<button id="Canvas-main-button-1" class="Canvas-main-button" name="{% url urldir %}">Agregar {{ botontitulo }}</button>