Alquiler_sqlite/Alquiler/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
#from django.conf.urls.statics import static 

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^banco/' , include('bancos.urls', namespace='bancos')),
    url(r'^caja/' , include('cajas.urls', namespace='cajas')),
    url(r'^cobranza/', include('cobranzas.urls', namespace='cobranzas')),
    url(r'^contrato/' , include('contratos.urls', namespace='contratos')),
    url(r'^gasto/' , include('gastos.urls', namespace='gastos')),
    url(r'^inquilino/' , include('inquilinos.urls', namespace='inquilinos')),
    url(r'^local/' , include('locales.urls', namespace='locales')),
    url(r'^lote/' , include('lotes.urls', namespace='lotes')),
    url(r'^mantenimiento/' , include('mantenimientos.urls', namespace='mantenimientos')),
    url(r'^pago/' , include('pagos.urls', namespace='pagos')),
] # + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Alquiler_sqlite/cajas/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.CajaList.as_view(), name='list'),
	url(r'^(?P<pk>\d+)$', views.CajaDetail.as_view(), name='detail'),
	url(r'^nuevo$', views.CajaCreation.as_view(), name='new'),
	url(r'^editar/(?P<pk>\d+)$', views.CajaUpdate.as_view(), name='edit'),
]

Alquiler_sqlite/locales/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
	url(r'^$', views.LocalList.as_view(), name='list'),
	url(r'^(?P<pk>\d+)$', views.LocalDetail.as_view(), name='detail'),
	url(r'^nuevo$', views.LocalCreation.as_view(), name='new'),
	url(r'^editar/(?P<pk>\d+)$', views.LocalUpdate.as_view(), name='edit'),
]

Alquiler_sqlite/locales/models.py
from __future__ import unicode_literals

from django.db import models


class LocalTipo(models.Model):
	nombre = models.CharField(max_length=255, unique=True)

	def __str__(self):
		return self.nombre

	class Meta:
		ordering = ('nombre',)


class LocalDivision(models.Model):
	nombre = models.CharField(max_length=255, unique=True)

	def __str__(self):
		return self.nombre

	class Meta:
		ordering = ('nombre',)


class Local(models.Model):
	piso = models.PositiveIntegerField()
	tipo = models.ForeignKey(LocalTipo)
	numero = models.PositiveIntegerField()
	division = models.ForeignKey(LocalDivision, default=1)

	def __str__(self):
		return '%s %s %s' % (self.tipo, self.numero, self.division)

	class Meta:
		ordering = ('piso', 'tipo', 'numero', 'division',)
		unique_together = (("tipo", "numero", "division"),)

Alquiler_sqlite/locales/views.py
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import (
	CreateView,
	UpdateView,
	DeleteView,
)

from .models import Local, LocalTipo, Local


class LocalList(ListView):
	model = Local 

	def get_context_data(self, **kwargs):
		context = super(LocalList, self).get_context_data(**kwargs)
		context.update({'titulo': 'Lista de Locales'})
		return context


class LocalDetail(DetailView):
	model = Local

	def get_context_data(self, **kwargs):
		context = super(LocalDetail, self).get_context_data(**kwargs)
		context.update({'titulo': 'Detalle de Local'})
		return context


class LocalCreation(CreateView):
	model = Local
	success_url = reverse_lazy('locales:list')
	fields = ['piso', 'tipo', 'numero', 'division'] 

	def get_context_data(self, **kwargs):
		context = super(LocalCreation, self).get_context_data(**kwargs)
		context.update({'titulo': 'Nuevo Local'})
		return context


class LocalUpdate(UpdateView):
	model = Local
	success_url = reverse_lazy('locales:list')
	fields = ['piso', 'tipo', 'numero', 'division'] 

	def get_context_data(self, **kwargs):
		context = super(LocalUpdate, self).get_context_data(**kwargs)
		context.update({'titulo': 'Editar Local'})
		return context


class LocalDelete(DeleteView):
	model = Local
	success_url = reverse_lazy('locales:list')

	def get_context_data(self, **kwargs):
		context = super(LocalDelete, self).get_context_data(**kwargs)
		context.update({'titulo': 'Borrar Local'})
		return context

Alquiler_sqlite/templates/locales/local_detail.html
{% extends "base.html" %}

{% block page_title %}
	{{ titulo }}
{% endblock %}

{% block contenido %}
	<h1>Detalle del local</h1>
	<p>Piso: <i>{{ local.piso }}</i></p>
	<p>Local Tipo: <i>{{ local.tipo }}</i></p>
	<p>Local Numero: <i>{{ local.numero}}, {{ local.division }}</i></p>
	<p>
		<a href="{% url "locales:list" %}">Regresar</a>
	</p>
{% endblock %}

Alquiler_sqlite/templates/locales/local_form.html
{% extends "base.html" %}

{% block page_title %}
	{{ titulo }}
{% endblock %}

{% block contenido %}
	<h1>Locales</h1>
	<form method="post">
		{% csrf_token %}
		{{ form.as_p }}
	    <input type="submit" class="Canvas-main-button-grabar" value="Guardar" />
		<input type="button" class="Canvas-main-button-regresar" onclick="goBack()" value="Regresar" />
	</form>
{% endblock %}

Alquiler_sqlite/templates/locales/local_list.html
{% extends "base.html" %}

{% block page_title %}
	{{ titulo }}
{% endblock %}

{% block contenido %}
	{% include "form-button.html" with urldir="locales:new" %}
	<table id="listaLocal" class="Table-lista">
		<thead>
			<tr>
				<th>PISO</th>
				<th>TIPO</th>
				<th>NUMERO</th>
				<th>DIVISION</th>
				<th></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
		{% for local in object_list %}
			<tr>
				<td>{{ local.piso }}</td>
				<td>{{ local.tipo }}</td>
				<td>{{ local.numero }}</td>
				<td>{{ local.division }}</td>
				<td><a href="{% url "locales:detail" local.id %}">Ver</a></td>
				<td><a href="{% url "locales:edit" local.id %}">Editar</a></td>
			</tr>
		{% endfor %}
		</tbody>
	</table>
    <script type="text/javascript">
        $(function(){
            BotonAgregar();
        })
    </script>	
{% endblock %}