Alquiler_sqlite/Alquiler/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
#from django.conf.urls.statics import static 

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^banco/' , include('bancos.urls', namespace='bancos')),
    url(r'^caja/' , include('cajas.urls', namespace='cajas')),
    url(r'^cobranza/', include('cobranzas.urls', namespace='cobranzas')),
    url(r'^contrato/' , include('contratos.urls', namespace='contratos')),
    url(r'^gasto/' , include('gastos.urls', namespace='gastos')),
    url(r'^inquilino/' , include('inquilinos.urls', namespace='inquilinos')),
    url(r'^local/' , include('locales.urls', namespace='locales')),
    url(r'^lote/' , include('lotes.urls', namespace='lotes')),
    url(r'^mantenimiento/' , include('mantenimientos.urls', namespace='mantenimientos')),
    url(r'^pago/' , include('pagos.urls', namespace='pagos')),
] # + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Alquiler_sqlite/cajas/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.CajaList.as_view(), name='list'),
	url(r'^(?P<pk>\d+)$', views.CajaDetail.as_view(), name='detail'),
	url(r'^nuevo$', views.CajaCreation.as_view(), name='new'),
	url(r'^editar/(?P<pk>\d+)$', views.CajaUpdate.as_view(), name='edit'),
]

Alquiler_sqlite/cajas/models.py
from __future__ import unicode_literals

from django.db import models

from lotes.models import Lote
from pagos.models import Pago  


class Caja(models.Model):
	fecha = models.DateField()


class CajaLote(models.Model):
	caja = models.OneToOneField(Caja, primary_key=True)
	lote = models.ForeignKey(Lote)


class CajaPago(models.Model):
	caja = models.OneToOneField(Caja, primary_key=True)
	pago = models.ForeignKey(Pago)

Alquiler_sqlite/cajas/views.py
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import (
	CreateView,
	UpdateView,
	DeleteView,
)

from .models import Caja


class CajaList(ListView):
	model = Caja

	def get_context_data(self, **kwargs):
		context = super(CajaList, self).get_context_data(**kwargs)
		context.update({'titulo': 'Lista Caja'})
		return context


class CajaDetail(DetailView):
	model = Caja

	def get_context_data(self, **kwargs):
		context = super(CajaDetail, self).get_context_data(**kwargs)
		context.update({'titulo': 'Detalle'})
		return context


class CajaCreation(CreateView):
	model = Caja
	success_url = reverse_lazy('cajas:list')
	fields = ['id', 'fecha'] 

	def get_context_data(self, **kwargs):
		context = super(CajaCreation, self).get_context_data(**kwargs)
		context.update({'titulo': 'Nueva Transaccion'})
		return context


class CajaUpdate(UpdateView):
	model = Caja
	success_url = reverse_lazy('cajas:list')
	fields = ['id', 'fecha'] 

	def get_context_data(self, **kwargs):
		context = super(CajaUpdate, self).get_context_data(**kwargs)
		context.update({'titulo': 'Editar Transaccion'})
		return context

Alquiler_sqlite/templates/cajas/caja_detail.html
{% extends "base.html" %}

{% block page_title %}
    {{ titulo }}
{% endblock %}

{% block contenido %}
	<h1>{{ Transaccion <i>{{ caja.id }}</i> }}</h1>
	<p>Fecha: <i>{{ caja.fecha }}</i></p>
	<p>
	    <a href="{% url "cajas:list" %}">Regresar</a>
	</p>
{% endblock %}

Alquiler_sqlite/templates/cajas/caja_form.html
{% extends "base.html" %}

{% block page_title %}
    {{ titulo }}
{% endblock %}

{% block contenido %}
	<form method="post">
	    {% csrf_token %}
	    {{ form.as_p }}
	    <input type="submit" class="Canvas-main-button-grabar" value="Guardar" />
		<input type="button" class="Canvas-main-button-regresar" onclick="goBack()" value="Regresar" />
	</form>
{% endblock %}

Alquiler_sqlite/templates/cajas/caja_list.html
{% extends "base.html" %}

{% block page_title %}
    {{ titulo }}
{% endblock %}

{% block contenido %}
    {% include "form-button.html" with urldir="cajas:new" %}
    <table id="listaCaja" class="Table-lista">
        <caption>{{ titulo }}</caption>
        <thead>
            <tr>
                <th>ID</th>
                <th>FECHA</th>
                <th></th>
                <th></th>
            </tr>
        </thead> 
        <tbody>
        {% for lt in object_list %}
            <tr>
                <td>{{ lt.id }}</td>
                <td>{{ lt.fecha }}</td>
                <td><a href="{% url "cajas:detail" lt.id %}">Ver</a></td>
                <td><a href="{% url "cajas:edit" lt.id %}">Editar</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <script type="text/javascript">
        $(function(){
            BotonAgregar();
        })
    </script>  
{% endblock %}